version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/set_env.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: root
