name: DEV Server CI/CD

on:
  push:
    branches:
      - "dev"

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: spring-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot Application
        run: |
          ./gradlew clean build -x test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to EC2 using CodeDeploy
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Trigger CodeDeploy Deployment
        uses: aws-actions/aws-codedeploy-deploy@v1
        with:
          application-name: spring-app-codedeploy
          deployment-group: spring-app-deployment-group
          revision-location: |
            {
              "revisionType": "AppSpecContent",
              "appSpecContent": {
                "content": "version: 0.0\nos: linux\nfiles:\n  - source: /\n    destination: /home/ec2-user/app\nhooks:\n  AfterInstall:\n    - location: scripts/restart.sh\n      timeout: 300\n      runas: ec2-user"
              }
            }
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}