name: DEV Server CI/CD

on:
  push:
    branches:
      - "dev"

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: spring-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot Application
        run: |
          ./gradlew clean build -x test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/spring-app:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/spring-app:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to EC2 using CodeDeploy
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Make scripts executable
        run: |
          chmod +x scripts/restart.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create version file
        run: echo "${{ env.IMAGE_TAG }}" > version.txt

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name morgan-dev \
            --deployment-group-name morgan-dev-deployment-group-backend \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location "repository=KTB-2nd-Morgan/Board_BE,commitId=${GITHUB_SHA}"
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}